### ISSUE TITLE
Just pointing out a small bug with your website

### ISSUE THREAD

**Issue by djsnipa1** [rossmoody/Assembl#4]
I noticed this bug with a couple of your websites. I think they are nicely done so I wanted to bring this to your attention. I'm using an iPhone IOS 15.3.1, Safari. I refreshed multiple times, etc and still this persisted. If I can be of any help, let me know.

--Chad

![image](https://user-images.githubusercontent.com/118037/185355440-1f6d30d7-57eb-47cc-b742-5a6a690c9cbf.png)

![image](https://user-images.githubusercontent.com/118037/185355519-3e6ca460-7409-43fe-b7d0-a46eb7e64741.png)

**Comment by rossmoody** [comment]
Thanks for the heads up! I thought maybe this had to do with it being an in-app browser context but I can't reproduce it on my phone. Gonna close for now, but I'll keep an eye on it and thanks for the report.
