### ISSUE TITLE
Preferences Not Showing

### ISSUE THREAD

**Issue by x1foideo** [rossmoody/Assembl#5]
When trying to open the Preferences Panel, it doesn't show up.
However, the other Options show up.

**Comment by rossmoody** [comment]
Do you mean the Preferences window or the Preference option next to the Apple icon in the top menu?

**Comment by x1foideo** [comment]
I mean, when clicking "Preferences" (cmd + ,) from the dropdown menu,from Assemble icon on the top bar.

<img width="177" alt="Screenshot 2022-10-10 alle 15 56 32" src="https://user-images.githubusercontent.com/12828790/194883018-05531f66-77a4-4cf1-807c-7e4a2ebeb35d.png">
